airbnb:
  outputs:
    staging:                                                          #Declaramos perfil para testing
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"

      role: TRANSFORM
      private_key: "{{ env_var('PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('PRIVATE_KEY_PASSPHRASE') }}"

      database: AIRBNB
      schema: STAGING
      threads: 4                        #Para trabajar con microbatches subimos threads = 4, de esta forma se podrá ejecutar 4 transformaciones a la vez
      warehouse: COMPUTE_WH

    prod:                                                             #Declaramos perfil para produccion
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"

      role: TRANSFORM
      private_key: "{{ env_var('PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('PRIVATE_KEY_PASSPHRASE') }}"

      database: AIRBNB
      schema: PROD
      threads: 4                        #Para trabajar con microbatches subimos threads = 4, de esta forma se podrá ejecutar 4 transformaciones a la vez
      warehouse: COMPUTE_WH

    dev:                                                              #Declaramos perfil para desarrollo
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"

      role: TRANSFORM
      private_key: "{{ env_var('PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('PRIVATE_KEY_PASSPHRASE') }}"

      database: AIRBNB
      schema: "DBT_{{ env_var('DBT_ENV_NAME') | upper | trim }}"      #Declaramos nombre del esquema: sera prefijo dbt_(nombre) en mayuscula y sin espacions
      threads: 4                        #Para trabajar con microbatches subimos threads = 4, de esta forma se podrá ejecutar 4 transformaciones a la vez
      warehouse: COMPUTE_WH
 
  target: dev
